exclude:
  - local.sh
  - README.md
  - CNAME
collections:
  articles:
    output: true
    permalink: /articles/:path/

description: "aquariums and fish wiki"
title: aquariums.wiki
url: https://aquariums.wiki
permalink: /:year/:month/:slug/
